src/ChimaeraArtSiteMVC/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChimLib.Database;
using ChimLib.Utils;

namespace ChimaeraArtSiteMVC.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Add(string ID, string Size)
        {
            HttpStatusCodeResult result = new HttpStatusCodeResult(System.Net.HttpStatusCode.InternalServerError);
            Guid cartKey;
            if (Request.Cookies.Get("cartKey") == null)
            {
                cartKey = Guid.NewGuid();

                List<SqlParameter> gp = new List<SqlParameter>();
                gp.Add(new SqlParameter("@GUID", cartKey));
                DB.Set("CartCreate", gp.ToArray());

                Response.Cookies["cartKey"].Value = cartKey.ToString();
                Response.Cookies["cartKey"].Expires = DateTime.Now.AddMonths(1);
            }
            else
            {
                cartKey = Guid.Parse(Request.Cookies["cartKey"].Value);
            }

            List<SqlParameter> p = new List<SqlParameter>();
            p.Add(new SqlParameter("@GUID", cartKey));

            DataTable dtCart = DB.Get("CartIDSelect", p.ToArray());
            if (dtCart != null && dtCart.Rows.Count > 0)
            {
                int CartID = (int)dtCart.Rows[0][0];

                List<SqlParameter> cp = new List<SqlParameter>();
                cp.Add(new SqlParameter("@CartID", CartID));
                cp.Add(new SqlParameter("@VariationID", ID));

                DataTable dtCartItems = DB.Get("CartItemSelect", cp.ToArray());
                if (dtCartItems == null || dtCartItems.Rows.Count <= 0)
                {
                    string DesignID = ScalablePressUtils.GetDesignID(ID);
                    if (string.IsNullOrWhiteSpace(DesignID))
                    {
                        Exception ex = new Exception("Design ID not found for variation ID " + ID);
                        LoggingUtil.InsertError(ex);
                    }
                    else
                    {
                        cp.Add(new SqlParameter("@DesignID", DesignID));
                    }
                }

                cp.Add(new SqlParameter("@ProductSize", Size));
                cp.Add(new SqlParameter("@Quantity", 1));

                try
                {
                    int iAffected = DB.SetWithRowsAffected("CartItemInsert", cp.ToArray());

                    if (iAffected > 0)
                        result = new HttpStatusCodeResult(System.Net.HttpStatusCode.OK);

                }
                catch (Exception ex)
                {
                    LoggingUtil.InsertError(ex);
                }
            }

            return result;
        }

        public ActionResult Remove(string ID)
        {
            try
            {
                List<SqlParameter> p = new List<SqlParameter>();
                p.Add(new SqlParameter("@CartItemID", ID));

                DB.Set("CartItemRemove", p.ToArray());
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.OK);
            }
            catch(Exception ex)
            {
                LoggingUtil.InsertError(ex);
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.InternalServerError);
            }
        }
    }
}

src/ChimaeraArtSiteMVC/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
using ChimaeraArtSiteMVC.Models;
using ChimLib.Database;

namespace ChimaeraArtSiteMVC.Controllers
{
    public class ShopController : Controller
    {
        // GET: Shop
        public ActionResult Index()
        {
            ProductSeries[] prods;

            using (SqlConnection conn = DB.GetConnection())
                prods = conn.Query<ProductSeries>("MVCProductSeries",
                    commandType: System.Data.CommandType.StoredProcedure).ToArray();

            return View(prods);
        }

        public ActionResult Product(int id)
        {
            ProductSeries ps = new ProductSeries();
            using (SqlConnection conn = DB.GetConnection())
                ps = conn.Query<ProductSeries>("MVCProductSeries",
                    new { SeriesID = id },
                    commandType: System.Data.CommandType.StoredProcedure).FirstOrDefault();

            ps.GetProducts();
            return View(ps);
        }
    }
}

src/ChimaeraArtSiteMVC/Views/Shop/Index.cshtml
@model IEnumerable<ChimaeraArtSiteMVC.Models.ProductSeries>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<div style="display:block;">
    @foreach (var series in Model)
    {

        <a href="@Url.Action("Product/" + series.ProductSeriesID, "Shop", null)" style="text-decoration:none;">
            <div class="productCell">
                <text class="imageText">@series.ProductSeriesName</text>
                <img src="@Url.Content(series.ProductSeriesImageURL)" alt="X" class="imageThumb" />
            </div>
        </a>
    }
</div>

<style type="text/css">
    .imageThumb {
	    max-width:180px;
	    width:80%;
	    clear:both;
	    display:table;
	    margin-left:auto;
	    margin-right:auto;
    }

    .productCell {
	    width:20%;
	    height:220px;
	    text-align:center;
	    display:inline-block;
	    vertical-align:top;
    }
</style>

src/ChimaeraArtSiteMVC/Views/Shop/Product.cshtml
@model ChimaeraArtSiteMVC.Models.ProductSeries

@{
    ViewBag.Title = @Model.ProductSeriesName;
}

<input id="previewSelection" type="hidden" value="@Model.Products[0].ProductVariationID" />

<table>
    <tr>
        <td class="productPreview">
            <img id="previewItem" class="imagePreview" src="@Model.Products[0].ProofURL" />
        </td>
        <td class="productDetail">
            <div>
                <h2 id="previewName">@Model.Products[0].ImageItem.ImageName - @Model.Products[0].Color.ProductColorDisplayName</h2>
                <p id="previewPrice">$@Model.Products[0].UnitPrice.ToString("0.00")</p>
                <hr />
                Size:
                <select id="previewSizes">
                    <option value="sml">Small</option>
                    <option value="med">Medium</option>
                    <option value="lrg">Large</option>
                    <option value="xlg">Extra Large</option>
                    <option value="xxl">2XL</option>
                    <option value="xxxl">3XL</option>
                </select>
                <hr />
                <p id="previewDescription">@Model.Products[0].ImageItem.ImageDescription</p>
                <br />
                <button id="btnAdd" type="button" onclick="addToCart()">ADD TO CART</button>
            </div>
        </td>
    </tr>
</table>

<div style="display:block">
    @foreach (var Product in Model.Products)
    {
        <a href="javascript:void(0);" onclick="@("variationSelected(" + Product.ProductVariationID + ")")" style="text-decoration:none;">
            <div class="variationCell">
                <img class="variationThumb" src="@Product.ProofURL" />
                <div class="imageText">$@Product.UnitPrice.ToString("0.00")</div>
            </div>
        </a>
    }
</div>

<script type="text/javascript">
    $(document).ready(function () {
        var data = getVariationData(getSelection());
    });

    function addToCart() {
        var id = getSelection();
        var size = getSize();
        var json = JSON.stringify({ ID: id, Size: size });
        $.ajax({
            type: "POST",
            url: '@Url.Action("Add", "Cart")',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            data: json
        })
        .success(function () {
            alert("Success");
        })
    }

    function getSelection() {
        var previewSelection = $("#previewSelection");
        return previewSelection.val();
    }

    function getSize() {
        var e = document.getElementById("previewSizes");
        var sizeSelected = e.options[e.selectedIndex].value;
        return sizeSelected;
    }

    function getVariationData(id) {
        var json = JSON.stringify({ID:id});
        $.ajax({
            type: "POST",
            url: '@Url.Content("~/Services/ShopServices.asmx/FetchVariationData")',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            data: json
        })
        .success(function (data) {
            var jsdata = data.d;

            var previewItem = $("#previewItem");
            var previewName = $("#previewName");
            var previewPrice = $("#previewPrice");
            var previewSizes = $("#previewSizes");
            var previewDescription = $("#previewDescription");

            previewName.text(jsdata.Name);
            previewItem.attr("src", jsdata.ProofURL);
            previewPrice.text('$' + jsdata.UnitPrice);
            previewSizes.empty();
            $.each(jsdata.Sizes, function (key, value) {
                previewSizes.append($("<option></option>").val(value).html(key))
            });
        });
    }

    function variationSelected(id) {
        var previewSelection = $("#previewSelection");
        previewSelection.val(id);
        getVariationData(id);
    }
</script>

<style type="text/css">
    .imagePreview {
	    max-width:580px;
	    max-height:670px;
        width:100%;
	    display:table;
	    clear:both;
    }

    .productDetail {
	    width:50%;
        padding-top:65px;
	    vertical-align:top;
	    text-align:left;
    }

    .productPreview {
	    width:50%;
    }

    .variationCell {
	    width:10%;
	    text-align:center;
	    display:inline-block;
	    vertical-align:top;
    }

    .variationThumb {
	    max-width:75px;
        max-height:75px;
        width:80%;
	    clear:both;
	    display:table;
	    margin-left:auto;
	    margin-right:auto;
    }
</style>